language: ruby
rvm:
 - 2.4

# Install dependencies
install:
  - bundle install
  - yarn install

# Build script
script:
  - npm run production-build
  - bash ./gh-pages_deploy.sh

# Deploy options
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _gh-pages
  repo: jcalcaben/devdocs
  target-branch: jcal/html-multi-test
  on:
    branch: jcalcaben/multi-branch-building